### ISSUE TITLE
Stop Button Not Working

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/track-extension#2145] opened 2023-01-06 22:16 UTC
* **OS version**: macOS latest
* **Browser version**: Chrome latest stable
* **Extension version**: 2.0.18

### 🐛 Describe the bug

Just what it says: stop button doesn't stop

### Expected behaviour

Stop button stops entry

### Steps to reproduce

Start entry
Try to click stop button
ta-daaah

### Other details or context

[Report](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309827994?view=List)
[Report](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309827991?view=List)

**Comment by TheSoloJake** [comment] 2023-01-06 22:46
[Report](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828016?view=List)

**Comment by TheSoloJake** [comment] 2023-01-06 22:57
[Report](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828020?view=List)

**Comment by TheSoloJake** [comment] 2023-01-06 23:00
[Report](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828021?view=List)

**Comment by TheSoloJake** [comment] 2023-01-06 23:02
[Report](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828022?view=List)

**Comment by TheSoloJake** [comment] 2023-01-06 23:59
[Report](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828028?view=List)

**Comment by TheSoloJake** [comment] 2023-01-07 03:48
[Report](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828037?view=List)
[Report](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309828032?view=List)

**Comment by rhys-vdw** [comment] 2023-01-07 04:08
I am finding this quite inconvenient. 😅

**Comment by lincetto** [comment] 2023-01-07 14:56
+1

**Comment by SlexBi** [comment] 2023-01-07 15:51
I'm confirming that for Chrome on Ubuntu. Issue appeared one or two days ago. I've reinstalled extension, updated Chrome, but nothing changed. Buttons "Stop" and "Refresh" don't work.

**Comment by 0ssamaak0** [comment] 2023-01-07 19:42
Confirming for Microsoft Edge (Version 108.0.1462.54) on Windows

**Comment by TheSoloJake** [comment] 2023-01-07 22:02
[User Report](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309828122?view=List)

[User Report](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309828127?view=List)

[User Report](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309828132?view=List)

[User Report](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309828161?view=List)

[User Report](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309828144?view=List)

[User Report](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309828145?view=List)

[User Report](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309828146?view=List)

[User Report](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309828147?view=List)

[User Report](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309828153?view=List)

**Comment by SlexBi** [comment] 2023-01-07 22:53
@TheSoloJake Your links are not available for users outside intercom.

**Comment by RobotRise** [comment] 2023-01-08 03:03
> * **OS version**: macOS latest
> * **Browser version**: Chrome latest stable
> * **Extension version**: 2.0.18
> 
> ### 🐛 Describe the bug
> Just what it says: stop button doesn't stop
> 
> ### Expected behaviour
> Stop button stops entry
> 
> ### Steps to reproduce
> Start entry Try to click stop button ta-daaah
> 
> ### Other details or context
> [Report](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309827994?view=List) [Report](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309827991?view=List)

Confirming issue on edge/windows

**Comment by TheSoloJake** [comment] 2023-01-08 06:58
> @TheSoloJake Your links are not available for users outside intercom.

That’s intentional. Intercom links are for Toggl employees’ internal use.

**Comment by nidarasheed** [comment] 2023-01-08 09:01
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828207?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 09:06
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828198?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 09:09
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828104?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 09:20
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828175?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 09:22
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828168?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 18:59
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828266?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 19:02
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828255?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 19:03
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828253?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 19:05
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828222?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 19:05
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828242?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 19:08
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828223?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 19:12
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828241?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 19:18
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828277?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 19:25
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309828231?view=List)

**Comment by nidarasheed** [comment] 2023-01-08 19:28
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828281?view=List)

**Comment by nicktoggl** [comment] 2023-01-08 23:52
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309828318)

**Comment by nicktoggl** [comment] 2023-01-08 23:54
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309828314)

**Comment by nicktoggl** [comment] 2023-01-08 23:56
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309828307)

**Comment by nicktoggl** [comment] 2023-01-09 00:02
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828306)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828297)

**Comment by nicktoggl** [comment] 2023-01-09 00:04
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828295)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828290)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828288)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828286)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828285)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828246)

**Comment by nicktoggl** [comment] 2023-01-09 01:25
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828321)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828323)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828326)

**Comment by nicktoggl** [comment] 2023-01-09 03:30
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828334)

**Comment by nicktoggl** [comment] 2023-01-09 04:17
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828347)

**Comment by nicktoggl** [comment] 2023-01-09 04:18
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828345)

**Comment by nicktoggl** [comment] 2023-01-09 05:03
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309828350)

**Comment by crbon** [comment] 2023-01-09 05:49
Confirming the issue is also present on edge/macos

**Comment by nidarasheed** [comment] 2023-01-09 06:40
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309828359?view=List)

**Comment by nidarasheed** [comment] 2023-01-09 06:41
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309828354?view=List)

**Comment by nidarasheed** [comment] 2023-01-09 07:07
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828366?view=List)

**Comment by nidarasheed** [comment] 2023-01-09 07:11
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309828053?view=List)

**Comment by nidarasheed** [comment] 2023-01-09 07:12
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309828111?view=List)

**Comment by ckamper** [comment] 2023-01-09 07:28
I can also confirm this for Chrome / Windows 11

**quick workaround for everybody until this is fixed:**

- In the browser extension, hover mouse over the running task
- right-click -> start timer (starts entry that says "Toggl Track Browser Extension")
- left-click on it -> delete (stops the timer, deleting that entry)
- you can start a new timer now, preserving the time entry from the previous one

**Comment by nidarasheed** [comment] 2023-01-09 07:35
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828371?view=List)

**Comment by nidarasheed** [comment] 2023-01-09 07:35
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828377?view=List)

**Comment by basilevs** [comment] 2023-01-09 08:10
Happens on Firefox 108.0.2 (64-bit) for Mac OS

**Comment by VeljkoTN** [comment] 2023-01-09 08:44
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828398?view=List)

**Comment by VeljkoTN** [comment] 2023-01-09 08:45
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828399?view=List)

**Comment by SlexBi** [comment] 2023-01-09 09:49
Chrome / Ubuntu - working now.

**Comment by nicktoggl** [comment] 2023-01-10 04:02
I have 2 users saying the issue is occasionally persisting, will troubleshoot with them first but re-opening for the moment.

For reference - https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309828323

**Comment by nicktoggl** [comment] 2023-01-16 23:22
Users haven't got back to us, so closing again.

**Closed by nicktoggl** 2023-01-16 23:22 UTC
Labels: bug

**Comment by rhys-vdw** [comment] 2023-01-16 23:59
I got this again yesterday too.

**Comment by isikyus** [comment] 2023-01-17 06:45
I'm seeing this intermittently in Firefox 108.0.2 on Ubuntu 18.04 (Toggl button extension version 2.0.18, last updated October 25th 2022). It doesn't look like there's a newer extension version than this available for Firefox.

**Comment by rhys-vdw** [comment] 2023-02-16 00:09
This is back in Chrome for me.

**Comment by nicktoggl** [comment] 2023-02-16 02:24
Another Chrome user reporting issues - [Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309839816)
